"""Dataset and split audit -- the numbers behind Table 1.

Plan section 4.1 requires every stated data figure to be regenerated by a
checksum-fixed analysis script rather than transcribed, so this module is the
only source of the counts Table 1 prints.

Two findings it exists to surface, both of which change how results must be
read:

  * ``Misleading`` has two rows in two different reports, so most rotations
    hold both out of Calibration and the class gets the documented bias
    fallback rather than an estimate;
  * the competition test split carries no labels, so every label-derived row of
    Table 1 has a Development value and no Test value.
"""

import json
from collections import Counter, defaultdict
from pathlib import Path
from statistics import median

from paper.data import REPO_ROOT, TEST_PATH, data_checksum, load_dev
from paper.labels import EVAL_FIELDS, FIELDS, row_to_state_id
from paper.train_config import PROTOCOLS, SEEDS

SPLITS_DIR = REPO_ROOT / "splits"


def load_test() -> list[dict]:
    """The 2,000 unlabelled competition test rows."""
    with open(TEST_PATH, encoding="utf-8") as f:
        return json.load(f)


def _labelled(rows) -> bool:
    """Whether the split carries the four label fields at all.

    Detected rather than assumed: the development split has them and the
    competition test split does not, and a Table 1 that filled the Test column
    from development numbers would be a fabricated cell.
    """
    return bool(rows) and all(field in rows[0] for field in FIELDS)


def _partition_audit(rows) -> dict:
    out = {
        "paragraphs": len(rows),
        "pdfs": len({r["pdf_url"] for r in rows}),
        "companies": len({r["company"] for r in rows}),
        "labelled": _labelled(rows),
    }
    sizes = sorted(Counter(r["pdf_url"] for r in rows).values())
    out["paragraphs_per_pdf"] = {
        "min": sizes[0], "median": int(median(sizes)), "max": sizes[-1],
    }
    if not out["labelled"]:
        return out

    state_ids = [row_to_state_id(r) for r in rows]
    out["legal_states_observed"] = len({s for s in state_ids if s >= 0})
    out["invalid_rows"] = sum(1 for s in state_ids if s < 0)
    out["class_support"] = {
        field: {lab: sum(1 for r in rows if r[field] == lab) for lab in labels}
        for field, labels in EVAL_FIELDS.items()
    }
    out["tuple_support"] = {
        str(s): n for s, n in sorted(Counter(state_ids).items())
    }
    return out


def _duplicate_texts(dev, test) -> dict:
    """Exact text duplicates, within development and across the two splits.

    Plan section 4.1 requires the known dev/test duplicate to be disclosed; the
    within-development check is here so that a future data drop introducing one
    cannot pass unnoticed.
    """
    dev_by_text = defaultdict(list)
    for r in dev:
        dev_by_text[r["data"]].append(r["id"])

    within = sorted(ids for ids in dev_by_text.values() if len(ids) > 1)
    across = sorted(
        [dev_by_text[t["data"]][0], t["id"]]
        for t in test if t["data"] in dev_by_text
    )
    return {"within_dev": within, "dev_test": across}


def _company_structure(rows) -> dict:
    """How companies and reports line up.

    Whether a document-disjoint split is also company-disjoint is a property of
    this corpus, not a further experiment: if no company contributes two
    reports, holding out a PDF holds out its company too. The reverse -- a
    single report covering more than one company -- is reported as found rather
    than assumed away.
    """
    from collections import defaultdict
    by_pdf, by_company = defaultdict(set), defaultdict(set)
    for row in rows:
        by_pdf[row["pdf_url"]].add(row["company"])
        by_company[row["company"]].add(row["pdf_url"])
    return {
        "companies": len(by_company),
        "tickers": len({row["ticker"] for row in rows}),
        "companies_in_multiple_reports":
            sum(1 for pdfs in by_company.values() if len(pdfs) > 1),
        "reports_with_multiple_companies":
            sum(1 for names in by_pdf.values() if len(names) > 1),
    }


def dataset_audit(dev=None, test=None) -> dict:
    dev = dev if dev is not None else load_dev()
    test = test if test is not None else load_test()

    dev_pdfs = {r["pdf_url"] for r in dev}
    test_pdfs = {r["pdf_url"] for r in test}
    return {
        "development": _partition_audit(dev),
        "test": _partition_audit(test),
        "pdf_overlap": {
            "n_shared": len(dev_pdfs & test_pdfs),
            "dev_only": len(dev_pdfs - test_pdfs),
            "test_only": len(test_pdfs - dev_pdfs),
        },
        "duplicates": _duplicate_texts(dev, test),
        "company_structure": _company_structure(dev),
        # The columns the release actually ships. Recorded so that a claim
        # about metadata the dataset does not carry -- a report year, for
        # instance, which a temporal split would need -- is checkable against
        # the deliverable instead of taken on trust.
        "dataset_fields": sorted(dev[0]),
    }


def split_audit(splits_dir=None, dev=None) -> dict:
    """Where the rare class lands once the folds are drawn.

    ``Misleading`` cannot have a bias estimated in any rotation whose
    Calibration partition contains none of its two rows. Counting those
    rotations is the post-hoc verification plan section 7 assigns to C; the
    split generator already records the fact per rotation in
    ``calibration_absent_classes``, and this recomputes it independently.
    """
    splits_dir = Path(splits_dir) if splits_dir is not None else SPLITS_DIR
    dev = dev if dev is not None else load_dev()

    misleading = [
        {"id": r["id"], "pdf_url": r["pdf_url"], "company": r["company"]}
        for r in dev if r["evidence_quality"] == "Misleading"
    ]
    mis_ids = {r["id"] for r in misleading}

    per_split, n_rotations, n_without = {}, 0, 0
    for protocol in PROTOCOLS:
        for seed in SEEDS:
            path = splits_dir / f"{protocol}_seed{seed}.json"
            with open(path, encoding="utf-8") as f:
                split = json.load(f)
            counts = [
                len(mis_ids & set(rot["calibration_ids"]))
                for rot in sorted(split["rotations"], key=lambda r: r["k"])
            ]
            per_split[f"{protocol}_seed{seed}"] = counts
            n_rotations += len(counts)
            n_without += sum(1 for c in counts if c == 0)

    return {
        "misleading_rows": misleading,
        "calibration_without_misleading": {
            "n_rotations": n_rotations,
            "n_without": n_without,
            "per_split": per_split,
        },
    }


def full_audit(dev=None, test=None, splits_dir=None) -> dict:
    dev = dev if dev is not None else load_dev()
    return {
        "data_checksum": data_checksum(dev),
        **dataset_audit(dev, test),
        "splits": split_audit(splits_dir, dev),
    }


def main() -> None:
    print(json.dumps(full_audit(), ensure_ascii=False, indent=1))


if __name__ == "__main__":
    main()
