"""Figure 1: the label hierarchy and the alternative decision routes.

The drawing itself lives in ``figures/figure1_hierarchy.tex`` as standalone
TikZ, so the figure's type matches the paper's. This module owns the part a
.tex file must not own: the numbers.

Plan section 5 asks one figure to carry four things -- the four-field
dependency and its 17 legal states, the base probabilities, the two
calibration options, and the three output rules -- and forbids one, which is
what drives the layout: it must not look like a four-layer architecture with
every module switched on. The main experiment compares mutually exclusive
routes, so calibration and decoding are drawn as parallel branches labelled
with the method ids that take them, never as stacked stages.

"所有數字由 script 生成，不手抄" applies to the figure as much as to the
tables. A hand-written .tex could simply type "17", so every count the figure
prints is emitted here into ``figure1_defs.tex`` and referenced by macro. The
label space is the single source: change ``paper.labels`` and the figure
follows, or the test suite says why it cannot.

Contract section 5 wants a vector PDF with fonts embedded; latexmk gives both,
and the fonts are the ACM template's own rather than the plotting defaults this
drawing replaced.
"""

import math
import shutil
import os
import subprocess
from pathlib import Path

from paper.labels import EVAL_FIELDS, NUM_LABELS, STATES

SOURCE = Path(__file__).resolve().parents[1] / "figures" / "figure1_hierarchy.tex"
DEFS_NAME = "figure1_defs.tex"

# Both PDFs this repository commits -- figure 1 and the tables preview, which
# embeds it -- have to rebuild to the same bytes, or `python -m analysis`
# leaves the working tree modified on every single run and the clean-clone
# reproduction can only ever speak for the .tex and caption files.
#
# pdfTeX varies two things between runs: the creation date, pinned here, and
# the trailer /ID, pinned by \pdftrailerid{} in the .tex sources because it is
# derived from the output path as well as the clock.
#
# 2026-08-23T00:00:00Z is the results freeze: a figure built after it draws a
# hierarchy that cannot change again.
SOURCE_DATE_EPOCH = 1787443200
LATEX_ENV = {"SOURCE_DATE_EPOCH": str(SOURCE_DATE_EPOCH),
             "FORCE_SOURCE_DATE": "1"}
LATEXMK = "latexmk"
TECTONIC = "tectonic"

_GENERATED_HEADER = (
    "% Generated by analysis/figure1.py from paper.labels -- do not edit.\n"
    "% Every number Figure 1 prints is defined here so that none is typed\n"
    "% into the drawing by hand.\n"
)


def _without_na(field: str) -> int:
    """Labels of ``field`` that name a real value rather than absence."""
    return len([x for x in EVAL_FIELDS[field] if x != "N/A"])


def state_counts() -> dict[str, int]:
    """Every count Figure 1 prints, derived from the frozen label space.

    Keys are the macro names the .tex source references, so a missing entry
    surfaces as an undefined control sequence rather than a silent blank.
    """
    combinations = math.prod(NUM_LABELS.values())
    return {
        "NumStates": len(STATES),
        "NumCombinations": combinations,
        "NumInvalid": combinations - len(STATES),
        "NumTimelines": _without_na("verification_timeline"),
        "NumQualities": _without_na("evidence_quality"),
        "NumPromiseLabels": NUM_LABELS["promise_status"],
        "NumTimelineLabels": NUM_LABELS["verification_timeline"],
        "NumEvidenceLabels": NUM_LABELS["evidence_status"],
        "NumQualityLabels": NUM_LABELS["evidence_quality"],
    }


def write_defs(path) -> Path:
    """Emit the macro definitions the figure source reads. Returns the path."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "".join(
        f"\\newcommand{{\\{name}}}{{{value}}}\n"
        for name, value in state_counts().items()
    )
    path.write_text(_GENERATED_HEADER + body, encoding="utf-8")
    return path


def tex_engine() -> str | None:
    """Return the preferred available standalone TeX compiler."""
    for name in (LATEXMK, TECTONIC):
        if shutil.which(name) is not None:
            return name
    return None


def tex_available() -> bool:
    """Whether this machine can rebuild the figure.

    Drawing in TikZ buys the paper's own type, and costs a TeX dependency the
    matplotlib version did not have. ``__main__`` asks this first so that a
    machine without TeX still recomputes every table rather than dying on the
    figure -- the counts come from ``paper.labels``, not from the run, so a
    stale PDF cannot disagree with the tables it ships beside.
    """
    return tex_engine() is not None


def build(out_path) -> Path:
    """Render the figure and return the path written.

    ``out_path`` names the PDF; the TikZ source is copied next to it when the
    caller asks for a directory other than ``figures/``, so a throwaway
    ``--figures-dir`` still produces a self-contained build.
    """
    engine = tex_engine()
    if engine is None:
        raise RuntimeError(
            f"neither {LATEXMK} nor {TECTONIC} is on PATH, so Figure 1 cannot "
            "be rebuilt. Install a TeX distribution and re-run; the committed "
            "figures/figure1_hierarchy.pdf remains valid until then."
        )
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_defs(out_path.parent / DEFS_NAME)

    source = out_path.with_suffix(".tex")
    if source.resolve() != SOURCE.resolve():
        shutil.copy(SOURCE, source)

    # latexmk decides what still needs doing from the .fdb_latexmk it left
    # beside the output. A cache written by a differently-configured run makes
    # the next build inherit that configuration silently: the committed figure
    # once carried a wall-clock date while a fresh clone of the same commit
    # produced the pinned one, and both looked correct. Removing the state is
    # what makes the build depend on its inputs alone.
    for suffix in (".aux", ".fdb_latexmk", ".fls", ".log", ".synctex.gz"):
        source.with_suffix(suffix).unlink(missing_ok=True)

    command = (
        [LATEXMK, "-pdf", "-interaction=nonstopmode", "-halt-on-error",
         source.name]
        if engine == LATEXMK else
        [TECTONIC, source.name, "--outdir", ".", "--keep-logs", "--reruns", "1"]
    )
    result = subprocess.run(
        command,
        cwd=source.parent, capture_output=True, text=True,
        env={**os.environ, **LATEX_ENV},
    )
    log = source.with_suffix(".log")
    tail = log.read_text(errors="replace")[-2000:] if log.exists() else result.stdout[-2000:]
    if result.returncode != 0:
        raise RuntimeError(f"{engine} failed for {source}:\n{tail}")
    # A clean exit is not proof of a drawing: a run interrupted mid-write
    # leaves a truncated file behind, and a blank Figure 1 is the one defect
    # nobody catches by eye until the paper is printed.
    if not out_path.exists() or out_path.stat().st_size == 0:
        raise RuntimeError(
            f"{engine} exited 0 but {out_path} is missing or empty:\n{tail}"
        )
    return out_path


def main() -> None:
    from paper.data import REPO_ROOT

    print(f"wrote {build(REPO_ROOT / 'figures' / 'figure1_hierarchy.pdf')}")


if __name__ == "__main__":
    main()
