"""Figure 2: a vector view of the generated multilingual repair table.

The table remains the canonical numerical artifact because its provenance
manifest reaches all prediction files. This module deliberately parses that
generated table instead of recomputing or transcribing scores, then emits the
TeX macros used by the drawing. A table regeneration therefore moves the
figure in the same command, while a stale committed definitions file fails the
test suite.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

from analysis.figure1 import (
    LATEXMK,
    LATEX_ENV,
    TECTONIC,
    tex_engine,
)
from paper.data import REPO_ROOT

TABLE = REPO_ROOT / "tables" / "table7_multilingual_mechanism.tex"
SOURCE = REPO_ROOT / "figures" / "figure2_multilingual.tex"
DEFS_NAME = "figure2_defs.tex"
EXPECTED_LANGUAGES = ("Chinese", "English", "French", "Japanese", "Korean")

PLOT_ZERO = 14.15
PLOT_SCALE = 83.0

_ROW_START = re.compile(r"^([A-Za-z]+)(?: \(([^)]+)\))?\s*&")
_GENERATED_HEADER = (
    "% Generated by analysis/figure2.py from "
    "tables/table7_multilingual_mechanism.tex.\n"
    "% Do not edit: every printed result and marker coordinate comes from the\n"
    "% canonical generated table.\n"
)


def parse_table(path: Path = TABLE) -> list[dict]:
    """Parse the five canonical data rows from the generated TeX tabular."""
    path = Path(path)
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _ROW_START.match(line.strip())
        if match is None:
            continue
        language, corpus = match.groups()
        corpus = corpus or "ML-Promise"
        if language not in EXPECTED_LANGUAGES:
            continue
        parts = [part.strip() for part in line.strip().split("&")]
        if len(parts) != 7:
            raise ValueError(f"malformed multilingual table row: {line}")
        try:
            rows.append({
                "language": language,
                "corpus": corpus,
                "n_rows": int(parts[1].replace(",", "")),
                "m0_invalid_percent": float(parts[2].replace(r"\%", "")),
                "na_net": int(parts[3]),
                "substantive_net": int(parts[4]),
                "weighted_f1_delta": float(parts[5]),
                "tuple_delta": float(
                    parts[6]
                    .removesuffix(r"\\")
                    .strip()
                    .removeprefix(r"\textbf{")
                    .removesuffix("}")
                ),
            })
        except ValueError as error:
            raise ValueError(f"malformed multilingual table row: {line}") from error

    languages = tuple(row["language"] for row in rows)
    if languages != EXPECTED_LANGUAGES:
        raise ValueError(
            "multilingual figure requires exactly five language rows in order "
            f"{EXPECTED_LANGUAGES}; found {languages}"
        )
    return rows


def _tex_text(value: str) -> str:
    return value.replace("&", r"\&").replace("%", r"\%")


def _plot_x(value: float) -> float:
    return PLOT_ZERO + PLOT_SCALE * value


def write_defs(rows: list[dict], path: Path) -> Path:
    """Write every label, value, sign count, and marker coordinate for TikZ."""
    languages = tuple(row["language"] for row in rows)
    if languages != EXPECTED_LANGUAGES:
        raise ValueError(
            "figure definitions require the five canonical language rows; "
            f"found {languages}"
        )

    lines = [_GENERATED_HEADER]
    for row in rows:
        stem = row["language"]
        values = {
            "Label": _tex_text(row["language"]),
            "Corpus": _tex_text(row["corpus"]),
            "Rows": f"{row['n_rows']:,}",
            "Invalid": f"{row['m0_invalid_percent']:.2f}",
            "NaNet": f"{row['na_net']:+d}",
            "SubstNet": f"{row['substantive_net']:+d}",
            "WfDelta": f"{row['weighted_f1_delta']:+.4f}",
            "TupleDelta": f"{row['tuple_delta']:+.4f}",
            "WfX": f"{_plot_x(row['weighted_f1_delta']):.4f}",
            "TupleX": f"{_plot_x(row['tuple_delta']):.4f}",
        }
        lines.extend(
            f"\\newcommand{{\\{stem}{suffix}}}{{{value}}}\n"
            for suffix, value in values.items()
        )

    lines.extend([
        f"\\newcommand{{\\LanguageCount}}{{{len(rows)}}}\n",
        "\\newcommand{\\TuplePositiveCount}{"
        f"{sum(row['tuple_delta'] > 0 for row in rows)}}}\n",
        "\\newcommand{\\WfPositiveCount}{"
        f"{sum(row['weighted_f1_delta'] > 0 for row in rows)}}}\n",
    ])
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(lines), encoding="utf-8")
    return path


def build(table_path: Path = TABLE, out_path: Path | None = None) -> Path:
    """Render Figure 2 from the generated table and return the PDF path."""
    out_path = Path(out_path or SOURCE.with_suffix(".pdf"))
    engine = tex_engine()
    if engine is None:
        raise RuntimeError(
            f"neither {LATEXMK} nor {TECTONIC} is on PATH, so Figure 2 cannot "
            "be rebuilt"
        )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_defs(parse_table(table_path), out_path.parent / DEFS_NAME)

    source = out_path.with_suffix(".tex")
    if source.resolve() != SOURCE.resolve():
        shutil.copy(SOURCE, source)
    for suffix in (".aux", ".fdb_latexmk", ".fls", ".log", ".synctex.gz"):
        source.with_suffix(suffix).unlink(missing_ok=True)

    command = (
        [LATEXMK, "-pdf", "-interaction=nonstopmode", "-halt-on-error", source.name]
        if engine == LATEXMK else
        [TECTONIC, source.name, "--outdir", ".", "--keep-logs", "--reruns", "1"]
    )
    result = subprocess.run(
        command,
        cwd=source.parent,
        capture_output=True,
        text=True,
        env={**os.environ, **LATEX_ENV},
    )
    log = source.with_suffix(".log")
    tail = (
        log.read_text(errors="replace")[-2000:]
        if log.exists() else result.stdout[-2000:]
    )
    if result.returncode != 0:
        raise RuntimeError(f"{engine} failed for {source}:\n{tail}")
    if not out_path.exists() or out_path.stat().st_size == 0:
        raise RuntimeError(
            f"{engine} exited 0 but {out_path} is missing or empty:\n{tail}"
        )
    return out_path


def main() -> None:
    print(f"wrote {build()}")


if __name__ == "__main__":
    main()
