"""What the intervals license D to write, computed rather than agreed verbally.

C is the only person who watched the resampling. Handing over a table and
leaving the phrasing to whoever writes the Results section is how "no
detectable difference" turns into "no difference" somewhere between a
spreadsheet and a submitted paper. The two statements are not
interchangeable: the first is what a wide interval supports, the second is a
claim about the world that 49 PDF clusters cannot carry.

So the classification is a function of the intervals, and the prohibitions
travel with the numbers instead of living in someone's memory.

Not a contract-4 deliverable. Plan section 9 picks the paper's title at the
freeze; this is the evidence that choice is made against.
"""

import json
from pathlib import Path

from paper.provenance import git_sha, now_iso


def classify_contrasts(contrasts) -> dict:
    """Split the pre-specified family by what its intervals exclude.

    ``undetermined`` is deliberately not called "null": an interval spanning
    zero means the study could not resolve the sign, not that the effect is
    absent.
    """
    better, worse, undetermined = [], [], []
    for key, row in contrasts.items():
        if row["ci_low"] > 0:
            better.append(key)
        elif row["ci_high"] < 0:
            worse.append(key)
        else:
            undetermined.append(key)
    return {"better": better, "worse": worse, "undetermined": undetermined}


def _fmt(row):
    return (f"{row['delta']:+.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}]"
            f" — {row['description']}")


def build_findings(audit, contrasts, regimes, cases=None,
                   consistent_contrasts=None, tuple_contrasts=None,
                   methods=None) -> str:
    verdict = classify_contrasts(contrasts)
    dev = audit["development"]
    absent = audit["splits"]["calibration_without_misleading"]
    n_mis = len(audit["splits"]["misleading_rows"])

    out = ["# Findings brief", "",
           "Generated by `analysis/findings.py`. Every number here comes from the "
           "same run that produced `tables/`. **Do not transcribe these figures "
           "into the paper** — the tabulars and their captions are the "
           "deliverables; this file exists to say what they license.", ""]

    out += ["## Primary metric — weighted macro-F1 (the competition ranks on this)",
            ""]
    if verdict["better"]:
        for k in verdict["better"]:
            out.append(f"- **{k}** is better: {_fmt(contrasts[k])}")
    else:
        out.append("- **None.** No pre-specified contrast showed a positive "
                   "effect whose Holm-corrected interval excludes zero.")
    for k in verdict["worse"]:
        out.append(f"- **{k}** is *worse*, and the interval excludes zero: "
                   f"{_fmt(contrasts[k])}")
    out.append("")

    if consistent_contrasts:
        second = classify_contrasts(consistent_contrasts)
        out += ["## Secondary metric — path-constrained weighted macro-F1 "
                "(the official metric, consistency-aware)",
                "",
                "Same five pre-specified contrasts, same resamples, corrected as "
                "its own Holm family. This is the official metric with one "
                "change and no others: a field whose ancestors were not "
                "predicted counts as a false prediction instead of being scored "
                "on its own. A difference between the two families is therefore "
                "attributable to that single factor — which is why this metric "
                "and not whole-row accuracy carries the secondary family.", ""]
        for k in second["better"]:
            out.append(f"- **{k}** is better: {_fmt(consistent_contrasts[k])}")
        for k in second["worse"]:
            out.append(f"- **{k}** is *worse*: {_fmt(consistent_contrasts[k])}")
        for k in second["undetermined"]:
            out.append(f"- **{k}**: no detectable difference — "
                       f"{_fmt(consistent_contrasts[k])}")
        out.append("")

        crossed = [k for k in contrasts
                   if k in consistent_contrasts
                   and (k in verdict["undetermined"])
                   != (k in second["undetermined"])]
        if crossed:
            out += ["### Where the two metrics disagree", "",
                    "These contrasts are resolved by one family and not the "
                    "other. The two metrics differ in exactly one respect — "
                    "whether a prediction its own ancestors do not support is "
                    "scored on its own merits — so a disagreement localises the "
                    "effect to that respect and nothing else. This is the "
                    "study's central observation, not an inconsistency to be "
                    "reconciled.", ""]
            for k in crossed:
                out.append(f"- **{k}**: weighted macro-F1 {_fmt(contrasts[k])}; "
                           f"path-constrained "
                           f"{_fmt(consistent_contrasts[k])}")
            out.append("")

    if tuple_contrasts:
        third = classify_contrasts(tuple_contrasts)
        out += ["## Also reported — whole-row tuple accuracy",
                "",
                "Pre-specified in the analysis plan as the secondary reporting "
                "metric, and reported in full for that reason. It no longer "
                "carries the argument — it changes two things at once relative "
                "to the official metric, per-field to per-row and partial "
                "credit to all-or-nothing, so a difference cannot be attributed "
                "to either — but it was named in advance and one of its "
                "contrasts runs against the methods. Dropping a planned family "
                "after seeing which way it pointed is selective reporting.", ""]
        for k in third["better"]:
            out.append(f"- **{k}** is better: {_fmt(tuple_contrasts[k])}")
        for k in third["worse"]:
            out.append(f"- **{k}** is *worse*: {_fmt(tuple_contrasts[k])}")
        for k in third["undetermined"]:
            out.append(f"- **{k}**: no detectable difference — "
                       f"{_fmt(tuple_contrasts[k])}")
        out.append("")

    if methods:
        out += ["## Conditional field F1 (plan §4.5)", "",
                "Each child field scored only on the rows its **gold** parent "
                "admits: `verification_timeline` and `evidence_status` on gold "
                "`promise_status = Yes`, `evidence_quality` on gold "
                "`evidence_status = Yes`. The conditioned rows are the same for "
                "every method, so the columns stay comparable. `promise_status` "
                "has no parent and is unchanged by construction.", "",
                "Reported because the unconditioned score mixes two questions — "
                "choosing the right child label, and repeating the `N/A` the "
                "hierarchy already fixes — and the second is easy for every "
                "method. **The competition still ranks on the unconditioned "
                "score**; this one is diagnostic.", ""]
        fields = [f for f in next(iter(methods.values()))["per_field_mean"]]
        out.append("| Method | " + " | ".join(
            f"{f} (all / conditioned)" for f in fields) + " |")
        out.append("|---|" + "---|" * len(fields))
        for method, row in methods.items():
            cells = " | ".join(
                f"{row['per_field_mean'][f]:.3f} / "
                f"{row['conditional_per_field_mean'][f]:.3f}" for f in fields)
            out.append(f"| {method} | {cells} |")
        out.append("")

    if regimes:
        out += ["## Evaluation regime", ""]
        for name, row in regimes.items():
            sig = "excludes zero" if (row["ci_low"] > 0 or row["ci_high"] < 0) \
                  else "spans zero"
            out.append(
                f"- **{name}**: same-document {row['same_document']:.3f} vs "
                f"document-disjoint {row['document_disjoint']:.3f}, "
                f"Δ {row['delta']:.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}] "
                f"({sig})")
        out.append("")

    out += ["## Claims the primary metric cannot resolve", "",
            "These are not statements that the effect is absent, and several are "
            "resolved by the secondary metric above. Each interval below spans "
            "zero on weighted macro-F1, which means this design could not "
            "resolve the sign *on the metric the competition ranks by*:", ""]
    for k in verdict["undetermined"]:
        out.append(f"- **{k}**: no detectable difference — {_fmt(contrasts[k])}")
    out += ["",
            "Write these as *no detectable difference*, never as *no difference* "
            "and never as *equivalent*.", ""]

    out += ["## Prohibitions", "",
            f"- **`Misleading` (n={n_mis}) must not carry any significance or "
            f"improvement claim.** It is absent from the Calibration partition "
            f"of {absent['n_without']} of the {absent['n_rotations']} rotations, "
            "so most rotations cannot estimate a bias for it at all.",
            "- **The path-constrained family was not pre-specified.** It was "
            "adopted after the primary analysis because it isolates a single "
            "factor. Say so wherever its intervals appear; presenting it as a "
            "planned analysis would misrepresent how it was chosen.",
            "- **`±` in Table 2 is seed spread, not a confidence interval.** It "
            "describes the whole pipeline — fold assignment and training "
            "together — and must not be described as model stability.",
            f"- **Δ in Table 3 is the gap between two estimation targets, not a "
            f"bias.** Development and test draw on the same {dev['pdfs']} "
            "reports, so the same-document column is the competition's own "
            "distribution, not a mistake.", ""]

    if cases:
        t = cases["totals"]
        top = max(t["by_rule"].items(), key=lambda kv: kv[1])
        out += ["## Material for the Discussion", "",
                f"- Independent argmax emits {t['n_invalid']:,} illegal tuples "
                f"across {t['n_rows']:,} rows ({t['invalid_rate']*100:.2f}%); the "
                f"most common single violation is `{top[0]}` at {top[1]:,} "
                f"({top[1]/t['n_invalid']*100:.0f}%).",
                f"- Projection repairs {t['fields_repaired']:,} fields and "
                f"destroys {t['fields_destroyed']:,}, a net of "
                f"{t['net_fields']:+,} over {t['n_rows']*4:,} field slots.", ""]
        if "na" in t:
            na, sub = t["na"], t["substantive"]
            worst = min(t["by_class"].items(), key=lambda kv: kv[1]["net"])[0] \
                if t.get("by_class") else None
            out += [f"- **The exchange is not symmetric.** Repairs land on the "
                    f"`N/A` classes ({na['net']:+,}) while the damage falls on "
                    f"the substantive ones ({sub['net']:+,})"
                    + (f", worst on `{worst}`" if worst else "") + ". macro-F1 "
                    "weights every class equally and `N/A` is the easiest class "
                    "to predict, so the two nearly cancel in the official metric "
                    "while whole-row correctness rises.", ""]
        if cases.get("runs"):
            first = cases["runs"][0]["unobserved"]
            n_unobs = next(iter(first.values()))["n_unobserved_in_gold"]
            per_method = {
                m: sum(r["unobserved"][m]["n_emitted_unobserved"]
                       for r in cases["runs"])
                for m in first
            }
            reached = [m for m, n in per_method.items() if n]
            tally = ", ".join(f"{m} in {n}/{len(cases['runs'])} runs"
                              for m, n in per_method.items())
            out += [f"- {n_unobs} legal states never occur in gold. A decoder "
                    f"searching the full legal space can reach them: {tally}. "
                    + (f"Only the calibrated arms ({', '.join(reached)}) get "
                       "there, which makes this a fact about calibration raising "
                       "the rare classes rather than about the decoder itself."
                       if reached else
                       "None of them does, so the search space is effectively "
                       "the observed states.") , ""]

    return "\n".join(out)


def write_findings(out_dir, audit, contrasts, regimes, cases=None,
                   consistent_contrasts=None, tuple_contrasts=None,
                   methods=None) -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "findings.md"
    header = (f"<!-- generated {now_iso()} from {git_sha()} -->\n\n")
    path.write_text(header + build_findings(audit, contrasts, regimes, cases,
                                           consistent_contrasts,
                                           tuple_contrasts, methods),
                    encoding="utf-8")
    return path
