"""What the intervals license D to write, computed rather than agreed verbally.

C is the only person who watched the resampling. Handing over a table and
leaving the phrasing to whoever writes the Results section is how "no
detectable difference" turns into "no difference" somewhere between a
spreadsheet and a submitted paper. The two statements are not
interchangeable: the first is what a wide interval supports, the second is a
claim about the world that 49 PDF clusters cannot carry.

So the classification is a function of the intervals, and the prohibitions
travel with the numbers instead of living in someone's memory.

Not a contract-4 deliverable. Plan section 9 picks the paper's title at the
freeze; this is the evidence that choice is made against.
"""

import json
from pathlib import Path

from paper.provenance import git_sha, now_iso


def classify_contrasts(contrasts) -> dict:
    """Split the pre-specified family by what its intervals exclude.

    ``undetermined`` is deliberately not called "null": an interval spanning
    zero means the study could not resolve the sign, not that the effect is
    absent.
    """
    better, worse, undetermined = [], [], []
    for key, row in contrasts.items():
        if row["ci_low"] > 0:
            better.append(key)
        elif row["ci_high"] < 0:
            worse.append(key)
        else:
            undetermined.append(key)
    return {"better": better, "worse": worse, "undetermined": undetermined}


def _fmt(row):
    return (f"{row['delta']:+.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}]"
            f" — {row['description']}")


def build_findings(audit, contrasts, regimes, cases=None) -> str:
    verdict = classify_contrasts(contrasts)
    dev = audit["development"]
    absent = audit["splits"]["calibration_without_misleading"]
    n_mis = len(audit["splits"]["misleading_rows"])

    out = ["# Findings brief", "",
           "Generated by `analysis/findings.py`. Every number here comes from the "
           "same run that produced `tables/`. **Do not transcribe these figures "
           "into the paper** — the tabulars and their captions are the "
           "deliverables; this file exists to say what they license.", ""]

    out += ["## Claims the intervals support", ""]
    if verdict["better"]:
        for k in verdict["better"]:
            out.append(f"- **{k}** is better: {_fmt(contrasts[k])}")
    else:
        out.append("- **None.** No pre-specified contrast showed a positive "
                   "effect whose Holm-corrected interval excludes zero.")
    for k in verdict["worse"]:
        out.append(f"- **{k}** is *worse*, and the interval excludes zero: "
                   f"{_fmt(contrasts[k])}")
    out.append("")

    if regimes:
        out += ["## Evaluation regime", ""]
        for name, row in regimes.items():
            sig = "excludes zero" if (row["ci_low"] > 0 or row["ci_high"] < 0) \
                  else "spans zero"
            out.append(
                f"- **{name}**: same-document {row['same_document']:.3f} vs "
                f"document-disjoint {row['document_disjoint']:.3f}, "
                f"Δ {row['delta']:.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}] "
                f"({sig})")
        out.append("")

    out += ["## Claims the study cannot support", "",
            "These are not statements that the effect is absent. Each interval "
            "spans zero, which means this design could not resolve the sign:", ""]
    for k in verdict["undetermined"]:
        out.append(f"- **{k}**: no detectable difference — {_fmt(contrasts[k])}")
    out += ["",
            "Write these as *no detectable difference*, never as *no difference* "
            "and never as *equivalent*.", ""]

    out += ["## Prohibitions", "",
            f"- **`Misleading` (n={n_mis}) must not carry any significance or "
            f"improvement claim.** It is absent from the Calibration partition "
            f"of {absent['n_without']} of the {absent['n_rotations']} rotations, "
            "so most rotations cannot estimate a bias for it at all.",
            "- **`±` in Table 2 is seed spread, not a confidence interval.** It "
            "describes the whole pipeline — fold assignment and training "
            "together — and must not be described as model stability.",
            f"- **Δ in Table 3 is the gap between two estimation targets, not a "
            f"bias.** Development and test draw on the same {dev['pdfs']} "
            "reports, so the same-document column is the competition's own "
            "distribution, not a mistake.", ""]

    if cases:
        t = cases["totals"]
        top = max(t["by_rule"].items(), key=lambda kv: kv[1])
        out += ["## Material for the Discussion", "",
                f"- Independent argmax emits {t['n_invalid']:,} illegal tuples "
                f"across {t['n_rows']:,} rows ({t['invalid_rate']*100:.2f}%); the "
                f"most common single violation is `{top[0]}` at {top[1]:,} "
                f"({top[1]/t['n_invalid']*100:.0f}%).",
                f"- Projection repairs {t['fields_repaired']:,} fields and "
                f"destroys {t['fields_destroyed']:,}, a net of "
                f"{t['net_fields']:+,} over {t['n_rows']*4:,} field slots — which "
                "is why a field-wise metric barely moves while the invalid rate "
                "goes to zero.", ""]

    return "\n".join(out)


def write_findings(out_dir, audit, contrasts, regimes, cases=None) -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "findings.md"
    header = (f"<!-- generated {now_iso()} from {git_sha()} -->\n\n")
    path.write_text(header + build_findings(audit, contrasts, regimes, cases),
                    encoding="utf-8")
    return path
