"""What the intervals license D to write, computed rather than agreed verbally.

C is the only person who watched the resampling. Handing over a table and
leaving the phrasing to whoever writes the Results section is how "no
detectable difference" turns into "no difference" somewhere between a
spreadsheet and a submitted paper. The two statements are not
interchangeable: the first is what a wide interval supports, the second is a
claim about the world that 49 PDF clusters cannot carry.

So the classification is a function of the intervals, and the prohibitions
travel with the numbers instead of living in someone's memory.

Not a contract-4 deliverable. Plan section 9 picks the paper's title at the
freeze; this is the evidence that choice is made against.
"""

import json
from pathlib import Path

from paper.provenance import git_sha, now_iso


# The level every family is judged at. One number, in one place, so a verdict
# cannot quietly follow a different threshold from the one the paper states.
ALPHA = 0.05


def classify_contrasts(contrasts, alpha=ALPHA) -> dict:
    """Split a pre-specified family by its **Holm-corrected** p-values.

    The five contrasts are tested together, so the verdict has to come from the
    corrected p. The bootstrap percentile interval reported beside each Δ is
    *uncorrected*, and reading significance off it would reintroduce exactly
    the multiplicity Holm is there to remove -- a contrast can miss the
    correction while its raw interval still excludes zero, and in this study
    several do.

    Direction comes from the sign of the point estimate rather than from the
    interval, for the same reason.

    ``undetermined`` is deliberately not called "null": failing to survive the
    correction means the study could not resolve the sign, not that the effect
    is absent.
    """
    better, worse, undetermined = [], [], []
    for key, row in contrasts.items():
        if row.get("p_holm", 1.0) >= alpha:
            undetermined.append(key)
        elif row["delta"] > 0:
            better.append(key)
        else:
            worse.append(key)
    return {"better": better, "worse": worse, "undetermined": undetermined}


def _fmt(row):
    """Δ, its uncorrected interval, and the corrected p the verdict rests on."""
    return (f"{row['delta']:+.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}], "
            f"p_Holm={row.get('p_holm', float('nan')):.3f}"
            f" — {row['description']}")


def build_findings(audit, contrasts, regimes, cases=None,
                   consistent_contrasts=None, tuple_contrasts=None,
                   methods=None, hierarchical_contrasts=None) -> str:
    verdict = classify_contrasts(contrasts)
    dev = audit["development"]
    absent = audit["splits"]["calibration_without_misleading"]
    n_mis = len(audit["splits"]["misleading_rows"])

    out = ["# Findings brief", "",
           "Generated by `analysis/findings.py`. Every number here comes from the "
           "same run that produced `tables/`. **Do not transcribe these figures "
           "into the paper** — the tabulars and their captions are the "
           "deliverables; this file exists to say what they license.", ""]

    out += ["## Primary metric — weighted macro-F1 (the competition ranks on this)",
            ""]
    if verdict["better"]:
        for k in verdict["better"]:
            out.append(f"- **{k}** is better: {_fmt(contrasts[k])}")
    else:
        out.append("- **None.** No pre-specified contrast showed a positive "
                   "effect that survived the Holm correction.")
    for k in verdict["worse"]:
        out.append(f"- **{k}** is *worse*, and the interval excludes zero: "
                   f"{_fmt(contrasts[k])}")
    out.append("")

    if consistent_contrasts:
        second = classify_contrasts(consistent_contrasts)
        out += ["## Secondary metric — path-constrained weighted macro-F1 "
                "(the official metric, consistency-aware)",
                "",
                "Same five pre-specified contrasts, same resamples, corrected as "
                "its own Holm family. This is the official metric with one "
                "change and no others: a field whose ancestors were not "
                "predicted counts as a false prediction instead of being scored "
                "on its own. A difference between the two families is therefore "
                "attributable to that single factor — which is why this metric "
                "and not whole-row accuracy carries the secondary family.", ""]
        for k in second["better"]:
            out.append(f"- **{k}** is better: {_fmt(consistent_contrasts[k])}")
        for k in second["worse"]:
            out.append(f"- **{k}** is *worse*: {_fmt(consistent_contrasts[k])}")
        for k in second["undetermined"]:
            out.append(f"- **{k}**: no detectable difference — "
                       f"{_fmt(consistent_contrasts[k])}")
        out.append("")

        crossed = [k for k in contrasts
                   if k in consistent_contrasts
                   and (k in verdict["undetermined"])
                   != (k in second["undetermined"])]
        if crossed:
            out += ["### Where the two metrics disagree", "",
                    "These contrasts are resolved by one family and not the "
                    "other. The two metrics differ in exactly one respect — "
                    "whether a prediction its own ancestors do not support is "
                    "scored on its own merits — so a disagreement localises the "
                    "effect to that respect and nothing else. This is the "
                    "study's central observation, not an inconsistency to be "
                    "reconciled.", ""]
            for k in crossed:
                out.append(f"- **{k}**: weighted macro-F1 {_fmt(contrasts[k])}; "
                           f"path-constrained "
                           f"{_fmt(consistent_contrasts[k])}")
            out.append("")

    if tuple_contrasts:
        third = classify_contrasts(tuple_contrasts)
        out += ["## Also reported — whole-row tuple accuracy",
                "",
                "Pre-specified in the analysis plan as the secondary reporting "
                "metric, and reported in full for that reason. It no longer "
                "carries the argument — it changes two things at once relative "
                "to the official metric, per-field to per-row and partial "
                "credit to all-or-nothing, so a difference cannot be attributed "
                "to either — but it was named in advance and one of its "
                "contrasts runs against the methods. Dropping a planned family "
                "after seeing which way it pointed is selective reporting.", ""]
        for k in third["better"]:
            out.append(f"- **{k}** is better: {_fmt(tuple_contrasts[k])}")
        for k in third["worse"]:
            out.append(f"- **{k}** is *worse*: {_fmt(tuple_contrasts[k])}")
        for k in third["undetermined"]:
            out.append(f"- **{k}**: no detectable difference — "
                       f"{_fmt(tuple_contrasts[k])}")
        out.append("")

    if methods and any("hierarchical_mean" in row for row in methods.values()):
        out += ["## Metric study — the same runs under four scoring rules", "",
                "The official metric is one choice among several, and the "
                "choices disagree about which method is best. `hF` is the "
                "ancestor-based hierarchical F1 of the hierarchical-"
                "classification literature: each label is the set of nodes on "
                "its path, and hP, hR, hF are the micro-averaged set overlaps. "
                "It is reported because a reviewer asks for an established "
                "structure-aware metric, not one of our own.", ""]
        out.append("| Method | official wF1 | C-wF1 | hP | hR | hF |")
        out.append("|---|---|---|---|---|---|")
        for method, row in methods.items():
            h = row.get("hierarchical_mean")
            if not h:
                continue
            out.append(
                f"| {method} | {row['weighted_macro_f1_mean']:.4f} | "
                f"{row.get('consistent_weighted_macro_f1_mean', float('nan')):.4f} | "
                f"{h['hP']:.4f} | {h['hR']:.4f} | {h['hF']:.4f} |")
        ranked_official = max(methods, key=lambda m: methods[m]["weighted_macro_f1_mean"])
        ranked_h = max((m for m in methods if methods[m].get("hierarchical_mean")),
                       key=lambda m: methods[m]["hierarchical_mean"]["hF"])
        worst_official = min(methods, key=lambda m: methods[m]["weighted_macro_f1_mean"])
        note = (f"**The two metrics disagree about the winner: "
                f"{ranked_official} on the official metric, {ranked_h} on hF"
                + (f" — and {ranked_h} is the *worst* method on the official one"
                   if ranked_h == worst_official else "")
                + ".** State the ranking together with the metric that produced "
                  "it; a bare \"best method\" claim is not well defined here.")
        out += ["", note, ""]

    if hierarchical_contrasts:
        fourth = classify_contrasts(hierarchical_contrasts)
        out += ["### hF over the same five pre-specified contrasts", "",
                "Its own Holm family, like the others. ⚠️ **Also adopted after "
                "the primary analysis** — it answers a question about the "
                "literature's metric, and was not named in the plan.", ""]
        for k in fourth["better"]:
            out.append(f"- **{k}** is better: {_fmt(hierarchical_contrasts[k])}")
        for k in fourth["worse"]:
            out.append(f"- **{k}** is *worse*: {_fmt(hierarchical_contrasts[k])}")
        for k in fourth["undetermined"]:
            out.append(f"- **{k}**: no detectable difference — "
                       f"{_fmt(hierarchical_contrasts[k])}")
        out.append("")

    if methods:
        out += ["## Conditional field F1 (plan §4.5)", "",
                "Each child field scored only on the rows its **gold** parent "
                "admits: `verification_timeline` and `evidence_status` on gold "
                "`promise_status = Yes`, `evidence_quality` on gold "
                "`evidence_status = Yes`. The conditioned rows are the same for "
                "every method, so the columns stay comparable. `promise_status` "
                "has no parent and is unchanged by construction.", "",
                "Reported because the unconditioned score mixes two questions — "
                "choosing the right child label, and repeating the `N/A` the "
                "hierarchy already fixes — and the second is easy for every "
                "method. **The competition still ranks on the unconditioned "
                "score**; this one is diagnostic.", ""]
        fields = [f for f in next(iter(methods.values()))["per_field_mean"]]
        out.append("| Method | " + " | ".join(
            f"{f} (all / conditioned)" for f in fields) + " |")
        out.append("|---|" + "---|" * len(fields))
        for method, row in methods.items():
            cells = " | ".join(
                f"{row['per_field_mean'][f]:.3f} / "
                f"{row['conditional_per_field_mean'][f]:.3f}" for f in fields)
            out.append(f"| {method} | {cells} |")
        out.append("")

    if methods and any("weighted_macro_f1_mean_no_misleading" in row
                       for row in methods.values()):
        out += ["## Misleading-free sensitivity (plan §4.5)", "",
                "The official metric recomputed without the two gold "
                "`Misleading` paragraphs. It is the only aggregate the plan "
                "permits around a class with n=2, and it exists to show that no "
                "conclusion rests on those two rows.", ""]
        out.append("| Method | weighted macro-F1 | without `Misleading` | Δ |")
        out.append("|---|---|---|---|")
        for method, row in methods.items():
            full = row["weighted_macro_f1_mean"]
            free = row.get("weighted_macro_f1_mean_no_misleading")
            if free is None:
                continue
            out.append(f"| {method} | {full:.4f} | {free:.4f} | {free - full:+.4f} |")
        out += ["",
                "⚠️ The gap is a property of removing an unlearnable class from "
                "a macro average, **not** a result about the class.", ""]

    if regimes:
        out += ["## Evaluation regime", ""]
        for name, row in regimes.items():
            sig = "excludes zero" if (row["ci_low"] > 0 or row["ci_high"] < 0) \
                  else "spans zero"
            out.append(
                f"- **{name}**: same-document {row['same_document']:.3f} vs "
                f"document-disjoint {row['document_disjoint']:.3f}, "
                f"Δ {row['delta']:.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}] "
                f"({sig})")
        out.append("")

    out += ["## Claims the primary metric cannot resolve", "",
            "These are not statements that the effect is absent, and several are "
            "resolved by the secondary metric above. Each interval below spans "
            "zero on weighted macro-F1, which means this design could not "
            "resolve the sign *on the metric the competition ranks by*:", ""]
    for k in verdict["undetermined"]:
        out.append(f"- **{k}**: no detectable difference — {_fmt(contrasts[k])}")
    out += ["",
            "Write these as *no detectable difference*, never as *no difference* "
            "and never as *equivalent*.", ""]

    out += ["## Prohibitions", "",
            f"- **`Misleading` (n={n_mis}) must not carry any significance or "
            f"improvement claim.** It is absent from the Calibration partition "
            f"of {absent['n_without']} of the {absent['n_rotations']} rotations, "
            "so most rotations cannot estimate a bias for it at all.",
            "- **The bracketed intervals are uncorrected.** They are 95% "
            "bootstrap percentile intervals for one contrast at a time. With "
            "five contrasts tested together the verdict comes from "
            "`p_Holm`, and several contrasts in this study have an interval "
            "excluding zero while failing the correction. Never call a "
            "contrast significant because its interval misses zero.",
            "- **Never write that the official metric *systematically* "
            "underestimates structured decoding.** The evidence is one "
            "benchmark, one backbone and seven decision rules: it supports "
            "*can substantially understate* or *may fail to reflect improvements "
            "in structured-output validity* on this task, and nothing about the "
            "metric in general.",
            "- **The path-constrained family was not pre-specified.** It was "
            "adopted after the primary analysis because it isolates a single "
            "factor. Say so wherever its intervals appear; presenting it as a "
            "planned analysis would misrepresent how it was chosen.",
            "- **`±` in Table 2 is seed spread, not a confidence interval.** It "
            "describes the whole pipeline — fold assignment and training "
            "together — and must not be described as model stability.",
            f"- **Δ in Table 3 is the gap between two estimation targets, not a "
            f"bias.** Development and test draw on the same {dev['pdfs']} "
            "reports, so the same-document column is the competition's own "
            "distribution, not a mistake.", ""]

    if cases:
        t = cases["totals"]
        top = max(t["by_rule"].items(), key=lambda kv: kv[1])
        # A run with no illegal output is the outcome the constraints are for;
        # the brief has to survive it rather than divide by its count.
        share = (f" ({top[1] / t['n_invalid'] * 100:.0f}%)"
                 if t["n_invalid"] else "")
        out += ["## Material for the Discussion", "",
                f"- Independent argmax emits {t['n_invalid']:,} illegal tuples "
                f"across {t['n_rows']:,} rows ({t['invalid_rate']*100:.2f}%); the "
                f"most common single violation is `{top[0]}` at "
                f"{top[1]:,}{share}.",
                f"- Projection repairs {t['fields_repaired']:,} fields and "
                f"destroys {t['fields_destroyed']:,}, a net of "
                f"{t['net_fields']:+,} over {t['n_rows']*4:,} field slots.", ""]
        if "parent_overrides" in t:
            o = t["parent_overrides"]
            out += [f"- **The decoder makes the parent field *more* accurate and "
                    f"still loses whole rows.** Searching all 17 states revises "
                    f"`{'promise_status'}` on {o['n_changed']:,} of "
                    f"{o['n_rows']:,} rows relative to the projection on the same "
                    f"probabilities. On the field itself that is a net gain: "
                    f"{o['to_correct']:,} become correct against {o['to_wrong']:,} "
                    f"broken. On those same rows whole-tuple correctness falls "
                    f"from {o['tuple_correct_before']:,} to "
                    f"{o['tuple_correct_after']:,}. The exchange is asymmetric — "
                    f"repairing the parent rarely rescues the row, because the "
                    f"children are usually still wrong, while breaking the parent "
                    f"destroys the row outright. This is the mechanism behind "
                    f"M4-M1, and it is the opposite of the intuitive story that "
                    f"an unreliable field overturns a reliable one.", ""]

        if "na" in t:
            na, sub = t["na"], t["substantive"]
            worst = min(t["by_class"].items(), key=lambda kv: kv[1]["net"])[0] \
                if t.get("by_class") else None
            out += [f"- **The exchange is not symmetric.** Repairs land on the "
                    f"`N/A` classes ({na['net']:+,}) while the damage falls on "
                    f"the substantive ones ({sub['net']:+,})"
                    + (f", worst on `{worst}`" if worst else "") + ". macro-F1 "
                    "weights every class equally and `N/A` is the easiest class "
                    "to predict, so the two nearly cancel in the official metric "
                    "while whole-row correctness rises.", ""]
        instances = cases["runs"][0].get("misleading_cases") if cases.get("runs") else None
        if instances:
            out += ["", "**The two `Misleading` paragraphs, one by one** "
                    "(plan §4.5 allows the per-instance record and nothing "
                    "aggregated over two rows):", ""]
            for case in instances:
                guessed = ", ".join(f"{m}→`{p}`" for m, p in case["predicted"].items())
                out.append(f"- `{case['id']}` in {case['pdf_url']}: {guessed}")
            out.append("")

        if cases.get("runs") and cases["runs"][0].get("unobserved"):
            first = cases["runs"][0]["unobserved"]
            n_unobs = next(iter(first.values()))["n_unobserved_in_gold"]
            per_method = {
                m: sum(r["unobserved"][m]["n_emitted_unobserved"]
                       for r in cases["runs"])
                for m in first
            }
            reached = [m for m, n in per_method.items() if n]
            tally = ", ".join(f"{m} in {n}/{len(cases['runs'])} runs"
                              for m, n in per_method.items())
            out += [f"- {n_unobs} legal states never occur in gold. A decoder "
                    f"searching the full legal space can reach them: {tally}. "
                    + (f"Only the calibrated arms ({', '.join(reached)}) get "
                       "there, which makes this a fact about calibration raising "
                       "the rare classes rather than about the decoder itself."
                       if reached else
                       "None of them does, so the search space is effectively "
                       "the observed states.") , ""]

    return "\n".join(out)


def write_findings(out_dir, audit, contrasts, regimes, cases=None,
                   consistent_contrasts=None, tuple_contrasts=None,
                   methods=None, hierarchical_contrasts=None) -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "findings.md"
    header = (f"<!-- generated {now_iso()} from {git_sha()} -->\n\n")
    path.write_text(header + build_findings(audit, contrasts, regimes, cases,
                                           consistent_contrasts,
                                           tuple_contrasts, methods,
                                           hierarchical_contrasts),
                    encoding="utf-8")
    return path
