"""Render every delivered tabular into one PDF, so they can be looked at.

The `.tex` files carry a bare ``tabular`` and nothing else -- that is contract
section 5, and it is what lets D decide float placement and width under the
eight-page budget. The cost is that none of them compiles on its own, so the
only way anyone has been able to see a rendered table is to paste it into a
document by hand.

This wraps all of them, each with its caption underneath, into one standalone
PDF. It is a **convenience, not a deliverable**: nothing here reaches the
paper, no number is computed, and the file is regenerated on demand.

    python -m analysis.preview            # -> tables/preview.pdf
"""

import argparse
import os
import subprocess
import tempfile
from pathlib import Path

from analysis.figure1 import LATEX_ENV, tex_available
from analysis.tables import ALL_TABLE_FILES
from paper.data import REPO_ROOT

# Reproducibility is shared with figure 1, which this preview embeds: see
# analysis/figure1.py for why both PDFs need the clock and the trailer /ID
# pinned before they can be committed.

PREAMBLE = r"""\documentclass[11pt]{article}
\usepackage[a4paper,margin=2cm,landscape]{geometry}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{graphicx}
\usepackage{parskip}
\setlength{\parindent}{0pt}
% pdfTeX derives the trailer /ID from the time and the output path, both of
% which differ between runs even with SOURCE_DATE_EPOCH pinned.
\ifdefined\pdftrailerid\pdftrailerid{}\fi
% \includegraphics makes pdfTeX record the absolute path of the file it
% embedded as /PTEX.FileName. Two clones of one commit then produce previews
% differing in hundreds of thousands of bytes while being the same document.
\ifdefined\pdfsuppressptexinfo\pdfsuppressptexinfo=-1\fi
\begin{document}
\begin{center}\Large\textbf{Delivered tables --- preview}\end{center}
\emph{Not a deliverable. Layout here is arbitrary; the paper's floats are D's
call. Generated by \texttt{python -m analysis.preview}.}
\vspace{1em}
"""


def _escape(text) -> str:
    """Captions are plain text with a little TeX in them already.

    Only the characters that would abort the build are escaped, and only when
    they are not already part of a command or a maths group -- the captions are
    written by ``analysis/tables.py`` and legitimately contain ``$\\pm$`` and
    ``\\%``.
    """
    out, i = [], 0
    while i < len(text):
        ch = text[i]
        if ch == "\\" or ch == "$":
            out.append(ch)
            i += 1
            if i < len(text):
                out.append(text[i])
                i += 1
            continue
        out.append({"&": r"\&", "#": r"\#", "_": r"\_"}.get(ch, ch))
        i += 1
    return "".join(out)


def _body(tables_dir) -> list[str]:
    """The document body: every delivered table, in order, with its caption.

    A missing tabular raises. It used to be skipped, which is how a table stops
    reaching the paper without anything failing -- ``ALL_TABLE_FILES`` names it
    as delivered, the writer was never wired into ``python -m analysis``, and
    the preview simply comes out one page shorter. Table 7 did exactly that.
    """
    tables_dir = Path(tables_dir)
    body = [PREAMBLE]
    for name in ALL_TABLE_FILES:
        tabular = tables_dir / name
        if not tabular.exists():
            raise FileNotFoundError(
                f"{name} is listed in ALL_TABLE_FILES but absent from "
                f"{tables_dir}. Rebuild with `python -m analysis`; if it does "
                "not appear, its writer is not registered in "
                "analysis.tables.EXTERNAL_TABLES."
            )
        stem = name.removesuffix(".tex")
        caption = tables_dir / f"{stem}_caption.txt"
        body += [rf"\section*{{{_escape(stem)}}}",
                 r"\begin{center}\small",
                 tabular.read_text(encoding="utf-8"),
                 r"\end{center}"]
        if caption.exists():
            body += [r"\footnotesize", _escape(caption.read_text(encoding="utf-8")),
                     r"\normalsize"]
        body.append(r"\newpage")
    return body


def build(tables_dir=None, out_path=None) -> Path:
    """Compile the preview and return where it landed."""
    tables_dir = Path(tables_dir or REPO_ROOT / "tables")
    out_path = Path(out_path or tables_dir / "preview.pdf")
    if not tex_available():
        raise RuntimeError(
            "no latexmk on PATH. The preview needs TeX; the tables themselves "
            "do not -- `python -m analysis` still regenerates them."
        )

    body = _body(tables_dir)

    figure = REPO_ROOT / "figures" / "figure1_hierarchy.pdf"
    if figure.exists():
        body += [r"\section*{figure1\_hierarchy}",
                 rf"\begin{{center}}\includegraphics[width=0.95\textwidth]{{{figure}}}\end{{center}}"]
    body.append(r"\end{document}")

    with tempfile.TemporaryDirectory() as tmp:
        source = Path(tmp) / "preview.tex"
        source.write_text("\n".join(body), encoding="utf-8")
        subprocess.run(
            ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error",
             f"-outdir={tmp}", str(source)],
            check=True, capture_output=True, text=True,
            env={**os.environ, **LATEX_ENV})
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes((Path(tmp) / "preview.pdf").read_bytes())
    return out_path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tables-dir", type=Path, default=None)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()
    print(f"preview -> {build(args.tables_dir, args.out)}")


if __name__ == "__main__":
    main()
